add bluez with fix for ap6212

diff --git a/ap6212-bluetooth b/ap6212-bluetooth
--- a/ap6212-bluetooth
+++ b/ap6212-bluetooth
@@ -58,14 +58,19 @@ then
         rfkill unblock all
         echo "0" > /sys/class/rfkill/rfkill0/state
         echo "1" > /sys/class/rfkill/rfkill0/state
-        echo " " > /dev/$PORT
+        #on orangepi win following command never ends on first try... force to run with a timeout...
+        timeout 5s echo " " > /dev/$PORT
+        if [ $? != 0 ]; then
+                #timed out... retry
+                echo " " > /dev/$PORT
+        fi
         devmem2 0x1f00060 b 1
         echo 205 > /sys/class/gpio/export
         echo out > /sys/class/gpio/gpio205/direction
         echo 0 > /sys/class/gpio/gpio205/value
         echo 1 > /sys/class/gpio/gpio205/value
         sleep 0.1
-        hciattach /dev/$PORT bcm43xx 115200 flow
+        hciattach -t 20 /dev/$PORT bcm43xx 115200 flow
         hciconfig hci0 up﻿
 fi
 }
